### ISSUE TITLE
ModelGenerator.php error

### ISSUE THREAD

**Issue by fatnjazzy** [atk4/atk4#389]
Missing argument 1 for Page_ModelGenerator::findModels(), called in C:\projects\wamp\atk4\atk4-addons\mvc\Page\ModelGenerator.php on line 15 and defined

findModels signature is: 
function findModels($dir, &$models, $prefix = null);

but you call it like this:
$this->findModels();

**Comment by DarkSide666** [comment]
Issue moved to addons repository.
