### ISSUE TITLE
Field type: money

### ISSUE THREAD

**Issue by Eizens** [atk4/atk4#479]
In model set field type->("money");

In form(CRUD) add value that is 1000 or larger.

It's being saved. Next time when the form loads, the value has been formatted as "1,000.00". And when you try to save, error is being thrown: "Not a valid number".

**Comment by DarkSide666** [comment]
Yeah, but how about localization? What if user really wants to see localized number in his web form? Something like `123'456,78 EUR` (with thousands separator and comma not dot for example)?
Should localization of form fields be done in a different way?

**Comment by romaninsh** [comment]
php should deal with that, right?

http://php.net/manual/en/function.money-format.php

**Comment by DarkSide666** [comment]
I guess so. Depending on locale set on initialization of PHP script.
Same goes for number format (dot or comma and thousand separator).
Also date format could be localized.

I guess there should be nice and generic way how to do such localizations in ATK (in future).
