### ISSUE TITLE
CRUD issue with atk4

### ISSUE THREAD

**Issue by johndobsonRoR** [atk4/atk4#573]
There is a CRUD issue with the first example in the atk book, the update option used for a basic edit or checking a book out as borrowed fails to rewrite the row after edit (including ID) using the 'save' button, leaving the table in an unusable state. This raises another issue, I can't locate the database where the books are stored in order to 'drop' the table and start again - the example doesn't appear to reference the "config-default.php" file in the admin directory, the only way I can drop the database is to reboot my machine.

**Comment by DarkSide666** [comment]
Moved to atk4/book repository.
