### ISSUE TITLE
Paginator and QuickSearch conflict when results not within currently selected pagination

### ISSUE THREAD

**Issue by DanielTosello** [atk4/atk4#597]
Hey guys,

When a paginated Grid is quicksearched, no results are returned unless the page is set to (a value lower than ipp x pagination mark). I've just checked the model debug output and it appears that limits are applied to quicksearches based on the previous paginated location. From example, when generated from page 1:  

``` select SQL_CALC_FOUND_ROWS `Title`,`School`,`id` from `project` having (`Title` like "%the%" or `School` like "%the%") limit 0, 10 [:a_2, :a] ```

vs. when generated from page 2, ipp(10):

``` select SQL_CALC_FOUND_ROWS `Title`,`School`,`id` from `project` having (`Title` like "%test%" or `School` like "%test%") limit 20, 10 [:a_2, :a] ```

...which is ok provided there are more than 20 returned results, but otherwise returns 'No matching records found' without any pagination... which of course makes any actually returned results inaccessible and gives the user the incorrect impression that the data is not within the database. 

Is it possible to simply set pagination to 1 when quicksearch is used while pagination is active?

**Comment by DarkSide666** [comment]
@DanielTosello This should be fixed now. Can you please test it?

**Comment by DanielTosello** [comment]
Will do, as soon as i have time... will report back when i've tested. Thanks for the fix :)

**Comment by DanielTosello** [comment]
Tested, working. Thanks again!
