### ISSUE TITLE
Problem with boolean type of the model field

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [atk4/atk4#633]
class Model_Foo extends SQL_Model{
        $this->addField('is_true')->type('boolean');
    }

    class Model_Bar extends SQL_Model{
        $this->addField('is_true')->type('boolean');
    }

    $bar = $this->add('Model_Bar');
    $foo = $this->add('Model_Foo')->addCondition('is_true',$bar->getElement('is_true'))->count();

Expected SQL

    SELECT *,
    (SELECT COUNT(*) `is_true` 
    FROM `foo` 
    WHERE `foo`.`is_true` = `bar`.`is_true`    <---- look here
    ) `foo_is_true` 
    FROM `bar`

Generated SQL

    SELECT *,
    (SELECT COUNT(*) `is_true` 
    FROM `foo` 
    WHERE `foo`.`is_true` = 1    <---- look here
    ) `foo_is_true` 
    FROM `bar`

**Comment by DarkSide666** [comment]
From example above I would expect following SQL:

```
SELECT count(*)
FROM foo
WHERE foo.is_true = (SELECT bar.is_true FROM bar)
```

**Comment by romaninsh** [comment]
you need 

    $foo = $this->add('Model_Foo')->addCondition('is_true',$bar->getElement('is_true')->fieldExpr())->count();

**Comment by DarkSide666** [comment]
Oh, really, `fieldExpr()` is the key :)
