### ISSUE TITLE
lib/view/crud - addFrame() - needs a "final return"

### ISSUE THREAD

**Issue by hvdhotline** [atk4/atk4#675]
In the addFrame()-Function is a final return missing around Line 415.

**Comment by DarkSide666** [comment]
I don't see bug there. `addFrame` should return Page object or null/false otherwise. Returning nothing (so called `@return void`) I guess is the same as `return;` or `return null;`

**Comment by hvdhotline** [comment]
Okay. Tested it once again (without my added `return` on the last line for working in my case) and ... whatever. Sorry for bugging :-)
