### ISSUE TITLE
changes.md should be updated

### ISSUE THREAD

**Issue by DarkSide666** [atk4/atk4#677]
changes.md file should be updated with info about 4.3 and 4.3.1

**Comment by DarkSide666** [comment]
I guess release info can be copied here too.

**Comment by romaninsh** [comment]
Also 4.3.2 (pending release)

**Comment by DarkSide666** [comment]
done here: https://github.com/atk4/atk4/commit/9df05521ae19a5d7eb37a578e042b852ddb7be60
