### ISSUE TITLE
Remove unused or deprecated ATK classes

### ISSUE THREAD

**Issue by DarkSide666** [atk4/atk4#694]
* `ModelIO` is not used in ATK core and can be removed.
* `Paginator_Compat` is not defined, unused and deprecated.
* `MVCForm` and `MVCGrid` is deprecated and should be removed at last. Should use `Form` and `Grid` classes instead. Only dependency is in class `Page_EntityManager`, but we can fix that easily.
* Remove `Page_EntityManager` - deprecated long time ago

**Comment by romaninsh** [comment]
Agreed

**Comment by romaninsh** [comment]
Also Page_EntityManager can be removed. That's obsoleted by CRUD now.
