### ISSUE TITLE
Web.php (class App_Web) A non well formed numeric value encountered > php 7 and above. 

### ISSUE THREAD

**Issue by Daniel-Yonkov** [atk4/atk4#736]
Upon setting the **start_time** in the  **__construct()** it gives an error: 

> A non well formed numeric value encountered.

I used casting to float in order to fix the issue.
chage:
       `$this->start_time=time()+microtime();` 
to:
       ` $this->start_time=(float)time()+(float)microtime();`

**Comment by romaninsh** [comment]
This is fixed in 4.4 branch.

**Comment by Daniel-Yonkov** [comment]
Yep, thank you for the info 👍
