### ISSUE TITLE
The each() function is deprecated using PHP 7.2. 

### ISSUE THREAD

**Issue by Eizens** [atk4/atk4#739]
The error appears in: atk4/lib/<b>GiTemplate.php</b>:659]The each() function is deprecated. 

But at first glance it is not the only place using [each()](http://php.net/manual/en/function.each.php) function.

I was testing 4.4 branch.

**Comment by romaninsh** [comment]
please submit PR. My focus is on atk4/ui and atk4/data so no time to maintain legacy atk.
