### ISSUE TITLE
read only hidden fields showing all the time at the bottom of all the forms...  FIELD SQL  error: Attempting to change read-only field

### ISSUE THREAD

**Issue by rapgithub** [atk4/atk4#743]
When using save the data a strange hidden field is showing all the time at the bottom of all the forms...

FIELD SQL

and when using it with filestore now I see all the hidden fields of filestore showing up too and I cannot save because of this error: see the attached file

<img width="884" alt="screenshot 2018-11-18 at 19 16 53" src="https://user-images.githubusercontent.com/11996194/48676457-84fafc00-eb67-11e8-9cdb-6d616328f3be.png">

Any solution?
thanks!

**Comment by rapgithub** [comment]
I think I found a Bug in the file

ATK4/ui/src/FormLayout/Columns.php  replacing this file with an old version of ATK4 works fine...

I saw the code is different so now I have to find which line is causing this problem!!!
Please anyone to review it and patch the bug here!

thanks

**Comment by DarkSide666** [comment]
This should go in atk4/ui repo. atk4/atk4 is discontinuated.

**Comment by DarkSide666** [comment]
Field SQL showing up bug will be fixed here: https://github.com/atk4/ui/pull/597

**Comment by DarkSide666** [comment]
not sure how ATK4/ui/src/FormLayout/Columns.php file is related to atk4/atk4 repo.
This repo is discontinued. Closing.

**Comment by rapgithub** [comment]
I thin I should not use atk4/atk4 repo... and uninstall it then...

**Comment by rapgithub** [comment]
Got it !! thanks for letting me know it is discontinued!

**Comment by DarkSide666** [comment]
You have to start using atk4/data and atk4/ui to be safe that we support that and you get all newest fixes and features.
