### ISSUE TITLE
Dereference field has no affect on subquery after calling hasOne()

### ISSUE THREAD

**Issue by LostInTheWeb** [atk4/atk4#97]
Following from the question raised at

http://stackoverflow.com/questions/10392457/pathfinder-exception-unable-to-include-model-model-using-setmodel/10396547#comment16698871_10396547

The dereference_field can be set by $m->dereference_field, but my reading of the source code leads to the conclusion that because the Reference::setModel() called inside hasOne() generates the subquery using the dereference_field. Changing dereference_field after hasOne() has not affect on the subquery.

So I modified the hasOne() function to the following, where hasOne sets the dereferenced_field variable. However, this does not fix the problem of changing the dereference_field after hasOne has been called.

/atk4/lib/Model/Table.php

    /** Defines one to many association */
    function hasOne($model,$our_field=null,$display_field=null,$deref_field_name=null){
        if(!$our_field){
            if(!is_object($model)){
                $tmp=preg_replace('|^(.*/)?(.*)$|','\1Model_\2',$model);
                $tmp=new $tmp; // avoid recursion
            }else $tmp=$model;
            $our_field=($tmp->table).'_id';
        }
        $r=$this->add('Field_Reference',$our_field);
        $r->dereferenced_field=$deref_field_name;
        $r->setModel($model,$display_field);
        return $r;
    }

**Comment by DarkSide666** [comment]
Obsolete, should be fixed with https://github.com/atk4/atk4/commit/0917169d6d23d407432d7d1705240541da831894
