### ISSUE TITLE
Form_Field->set() should set to defaultValue

### ISSUE THREAD

**Issue by si4dev** [atk4/atk4#98]
Form_Field->set() should set to defaultValue and it isn't.

The Form_Field->getDefault() comments to be obsolete and refers to use ->set()

I tried with CRUD:

 if($c->form) {
      $f=$c->form->getElement('margin_ratio');
      if($f->get() == NULL) $f->set();

But get error that parameter is missing in set().

Or am I mistaken?

**Comment by DarkSide666** [comment]
It's addressed in `Form_Field` `loadPOST` and `setForm` methods. `set()` method should not set default value.
